In [ ]:
# Que-1. What is a parameter?

In [1]:
# - Parameter = A parameter is a variable used in a function definition to accept input values when the function is called. It acts as a placeholder for the actual values (arguments) that will be passed during the function call.
# Example in Python:

def greet(name):  # 'name' is the parameter
    print(f"Hello, {name}!")

greet("Gouri")  # "Gouri" is the argument

Hello, Gouri!


In [ ]:
# Key Points:

# Parameter: Defined in the function declaration to receive input.


# Argument: The actual value passed to the parameter during the function call.


In [ ]:
#Que-2. What is correlation?
# What does negative correlation mean?

In [ ]:
# - Correlation = Correlation is a statistical concept that measures the relationship between two variables. It shows how one variable changes in response to changes in another.

# Types of Correlation:

# 1. Positive Correlation: When one variable increases, the other also increases.
#     Example: Height and weight.


# 2. Negative Correlation: When one variable increases, the other decreases.
#     Example: Distance traveled and fuel remaining.


# 3. No Correlation: No relationship between the two variables.
#     Example: Shoe size and intelligence.
 

# Correlation Coefficient (r):

# It ranges from -1 to 1:

# 1: Perfect positive correlation

# -1: Perfect negative correlation

# 0: No correlation

# Negative Correlation = Negative correlation means that as one variable increases, the other variable decreases. It indicates an inverse relationship between the two variables.

In [ ]:
# Que-3. Define Machine Learning. What are the main components in Machine Learning?

In [ ]:
# - Machine Learning = Machine Learning (ML) is a method that allows computers to learn from data and make decisions or predictions without being specifically programmed for a task. It uses algorithms to identify patterns in data and improve performance over time.

# Main Components of Machine Learning
# Data:

# The raw information used to train the model.

# Example: Customer details, sales records, or weather data.



# Features:

# Specific inputs (variables) used to train the model.

# Example: Age, income, and location in a sales prediction model.



# Model:

# The formula or algorithm used to learn from data and make predictions.

# Example: Linear Regression, Decision Tree, or Neural Networks.



# Training:

# The process of teaching the model using data to recognize patterns.

# Example: Feeding past sales data to predict future sales.



# Testing:

# Checking how well the model works with new or unseen data.

# Example: Testing the model on this month's sales data to verify accuracy.



# Evaluation:

# Measuring the model's performance using metrics like accuracy or error rate.

# Example: If the prediction matches the actual data, the accuracy is high.


# Simple Example:

# Think of ML like teaching a child:

# Data: Child's books and lessons.

# Training: Teaching the child to solve problems by practicing with examples.

# Testing: Giving a new problem to see if they learned it.

# Model: The child’s brain learning how to solve problems.

In [ ]:
# Que-4. How does loss value help in determining whether the model is good or not?

In [ ]:
# - The loss value helps us understand how well the model is performing. It tells us how far the model's predictions are from the actual results.
# High Loss Value:

# If the loss is high, it means the model's predictions are far from the real values.

# The model is not performing well and needs improvement.

# Low Loss Value:

# A low loss means the model's predictions are close to the actual values.

# This indicates that the model is performing well and making accurate predictions.

# Why is Loss Important?

# The goal in machine learning is to minimize the loss value.

# A smaller loss value means the model is doing a good job of predicting, and the learning process is working.

# Simple Example:

# Think of it like shooting arrows at a target.

# If the arrows are far from the center (high loss), you're not hitting the target well.

# If the arrows are close to the center (low loss), you're hitting the target accurately.

# So, the loss value helps us understand if the model needs more training or if it's ready to be used.


In [ ]:
# Que-5. What are continuous and categorical variables?

In [ ]:
# - Continuous Variables

# Continuous variables are numerical variables that can take any value within a certain range and can be measured with great precision. These variables can have an infinite number of possible values, including decimals or fractions.

# Examples of Continuous Variables:
# Height (e.g., 5.5 feet, 6.2 feet)
# Weight (e.g., 60.5 kg, 70.3 kg)
# Time (e.g., 3.75 hours, 4.2 hours)


# Categorical Variables
# Categorical variables are variables that represent distinct groups or categories. These variables are usually qualitative and cannot be measured on a numerical scale. Categorical variables can be either nominal or ordinal.

# Nominal: Categories with no specific order.
# Example: Colors (Red, Blue, Green)

# Ordinal: Categories with a meaningful order, but the differences between the categories may not be uniform.
# Example: Education levels (High School, Bachelor's, Master's)


# Examples of Categorical Variables:
# Gender (Male, Female, Other)
# Marital status (Single, Married, Divorced)
# Types of products (Electronics, Furniture, Clothing)


# In summary:
    # Continuous variables can have infinite values within a range and are numeric.
    # Categorical variables represent distinct categories or groups, either with or without a specific order.

In [ ]:
# Que-6. How do we handle categorical variables in Machine Learning? What are the common techniques?

In [ ]:
# - Categorical variables need to be converted into numerical form to be used in machine learning models. Here are the common techniques:

# 1. Label Encoding:

# Converts categories into unique numbers.

# Example: Red → 0, Blue → 1, Green → 2.


# 2. One-Hot Encoding:

# Converts categories into binary vectors.

# Example: Red → [1, 0, 0], Blue → [0, 1, 0], Green → [0, 0, 1].


# 3. Ordinal Encoding:

# Used when categories have a natural order (e.g., Low, Medium, High → 0, 1, 2).


# 4. Frequency Encoding:

# Encodes categories based on their frequency in the dataset.


# Which to use?

# Use Label Encoding for ordered categories.

# Use One-Hot Encoding for unordered categories.

In [ ]:
# Que-7. What do you mean by training and testing a dataset?

In [ ]:
# - In Machine Learning, we split a dataset into two parts: training and testing.

# 1. Training Dataset:

# This is the part of the dataset used to train the model.

# The model learns from the training data by finding patterns and relationships between the features and the target variable.

# Example: If you're predicting house prices, the training data includes features like area, number of rooms, and price, so the model learns the relationship between them.

# 2. Testing Dataset:

# After training, we use the testing dataset to evaluate the model's performance.

# This data helps us check how well the model generalizes to new, unseen data.

# The testing data is not used during the training process, so the model is tested on how well it predicts outcomes for new examples.

# Example: The testing data might have similar features (area, number of rooms) but with different prices that the model has never seen before.


# Why Split the Data?

# Training helps the model learn.

# Testing helps us evaluate how well the model will perform on new, unseen data.


In [ ]:
#Que-8. What is sklearn.preprocessing?

In [7]:
# - sklearn.preprocessing
# The sklearn.preprocessing module provides various functions to preprocess data for machine learning models. Common tasks include scaling, encoding, and handling missing data.

# Key Functions and Examples:

# 1. StandardScaler:
# Standardizes data by removing the mean and scaling it to unit variance.

import numpy as np 
from sklearn.preprocessing import StandardScaler
#Sample Data
data = np.array ([[1, 2], [3,4], [5,6]])
# Apply StandardScaler 
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)  # data is the input data
print(scaled_data)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [8]:
# 2. MinMaxScaler:
# Scales data to a specified range, usually [0, 1].
from sklearn.preprocessing import MinMaxScaler
#Sample Data
data = np.array ([[1, 2], [3,4], [5,6]])
# Apply MinMaxScaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [10]:
# 3. LabelEncoder:
# Converts categorical labels into numeric values (useful for target variables).
from sklearn.preprocessing import LabelEncoder
#Sample Labels
labels = ['cat', 'dog', 'fish']
# Apply LabelEncoder
encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(labels)  # labels are the target labels
print(encoded_labels)

[0 1 2]


In [11]:
# 4. OneHotEncoder:
# Converts categorical features into one-hot encoded format (useful for features).
from sklearn.preprocessing import OneHotEncoder
#Sample Categorical data
data = np.array([['cat'],['dog'],['fish']])
#Apply OneHotEncoder
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data).toarray()  # data is the categorical feature data
print(encoded_data)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 5. SimpleImputer:
# Fills missing data with a specified strategy (mean, median, mode).
from sklearn.impute import SimpleImputer
# Sample data with missing values
data = np.array([[1,np.nan], [3,4], [5,6]])
# Apply SimpleImputer
imputer = SimpleImputer(strategy='mean')  # Use 'median' or 'most_frequent' if needed
imputed_data = imputer.fit_transform(data)  # data is the input with missing values
print(imputed_data)

[[1. 5.]
 [3. 4.]
 [5. 6.]]


In [ ]:
# Why Use Preprocessing?

# Preprocessing is essential to convert raw data into a format that is suitable for machine learning models. It helps improve model accuracy and performance.


In [ ]:
# Que-9. What is a Test set?

In [ ]:
# - A test set is a subset of the dataset that is used to evaluate the performance of a machine learning model after it has been trained.
# Key Points:

# Purpose: It is used to assess how well the trained model generalizes to new, unseen data.
# Not Used During Training: The test set is not involved in the training process; it is kept separate to provide an unbiased evaluation of the model’s performance.
# Evaluation: After the model is trained on the training set, the test set is used to make predictions, and its results are compared to the actual outcomes to calculate performance metrics like accuracy, precision, recall, etc.

# Why Use a Test Set?

# To ensure the model is not just memorizing the training data but is able to make accurate predictions on new data.


# Example:
# If you have a dataset of 1000 data points, you might split it into a training set (e.g., 80% of the data) and a test set (e.g., 20% of the data). You train the model on the training set and test it on the test set.


In [ ]:
# Que-10. How do we split data for model fitting (training and testing) in Python?
# How do you approach a Machine Learning problem?

In [16]:
# - How to Split Data for Model Fitting in Python:

# Use train_test_split to split your data:
from sklearn.model_selection import train_test_split

# Example data
data = [[1, 2], [3, 4], [5, 6], [7, 8]]  # Features
labels = [0, 1, 0, 1]  # Target labels

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

print("Training features:", X_train)
print("Test features:", X_test)



Training features: [[7, 8], [1, 2], [5, 6]]
Test features: [[3, 4]]


In [ ]:
# How to Approach a Machine Learning Problem:

# 1. Define the problem (e.g., classification or regression).


# 2. Prepare the data (clean and split into training and test sets).


# 3. Choose a model (e.g., decision tree, logistic regression).


# 4. Train the model using the training data.


# 5. Evaluate the model on the test set.


In [ ]:
# Que-11. Why do we have to perform EDA before fitting a model to the data?

In [ ]:
# - Why Perform EDA Before Fitting a Model?

# Exploratory Data Analysis (EDA) is important before fitting a machine learning model because:

# 1. Understand the Data:

# EDA helps you understand the dataset, including the distribution of data, relationships between variables, and potential patterns. Without this, you may miss important insights or errors in the data.


# 2. Handle Missing Values:

# It allows you to identify missing values and decide how to handle them (e.g., imputing or removing missing data).


# 3. Detect Outliers:

# EDA helps in identifying outliers that can distort the results of the model. You can decide whether to keep or remove them.


# 4. Feature Selection:

# EDA allows you to identify irrelevant or redundant features that can be removed to improve model performance and reduce complexity.


# 5. Check Data Distribution:

# Some models assume specific distributions (e.g., linear regression assumes normality). EDA helps check if this assumption holds or if transformations are needed.


# 6. Understand Relationships:

# Helps you identify relationships between variables (e.g., correlation), which can inform the choice of the model or features to include.


# 7. Improve Model Performance:

# By understanding the data through EDA, you can better preprocess the data (scaling, encoding), which directly improves model accuracy.


# Summary:

# Performing EDA is a crucial step that helps you understand and clean the data, making sure it's ready for modeling and leading to better model performance.


In [ ]:
# Que-12. What is correlation?

In [ ]:
# - Correlation basically tells us how two things are related to each other.

# Positive Correlation: When one thing goes up, the other also goes up. For example, if you study more, your marks might improve.

# Negative Correlation: When one thing goes up, the other goes down. For example, the more time you spend on social media, the less time you may have for studying.

# Zero Correlation: When there's no relationship between the two things. For example, your height and shoe size might not be related in any predictable way.


# The correlation coefficient (a number between -1 and 1) shows how strongly the two things are related. If it's closer to 1 or -1, the relationship is strong. If it's closer to 0, there's no relationship.

In [ ]:
# Que-13. What does negative correlation mean?

In [ ]:
# - Negative correlation means that when one variable increases, the other variable decreases, and vice versa.

# For example:

# Speed and travel time: The faster you go, the less time it takes to reach your destination. So, as speed increases, travel time decreases. This is a negative correlation.

# Temperature and heating bill: In colder months, you might use more heating, and as the temperature increases, the heating bill usually decreases.


# In simple terms, it's an inverse relationship: one thing goes up, the other goes down.


In [ ]:
#Que-14. How can you find correlation between variables in Python?

In [17]:
# - To find the correlation between variables in Python, you can use the corr() method from Pandas, which calculates the Pearson correlation coefficient.
# Steps:

# Import the required libraries:

# You'll need Pandas for data handling and NumPy for numerical operations.


# Use corr() method:

# This method calculates the correlation between all pairs of variables in a DataFrame.
# Example Code:

import pandas as pd

# Sample data
data = {'Variable1': [1, 2, 3, 4, 5],
        'Variable2': [5, 4, 3, 2, 1],
        'Variable3': [2, 3, 4, 5, 6]}
# Create DataFrame
df = pd.DataFrame(data)

# Calculate correlation between variables
correlation = df.corr()

print(correlation)

           Variable1  Variable2  Variable3
Variable1        1.0       -1.0        1.0
Variable2       -1.0        1.0       -1.0
Variable3        1.0       -1.0        1.0


In [ ]:
# Key Points:

# df.corr() calculates the correlation matrix for all numeric columns in the DataFrame.

# The values range from -1 to 1:

# 1: Perfect positive correlation

# -1: Perfect negative correlation

# 0: No correlation

# This is how you can easily find the correlation between variables in Python. 

In [ ]:
#Que-15.What is causation? Explain difference between correlation and causation with an example.

In [ ]:
# -Causation refers to a relationship where one event or variable directly causes another to happen. In other words, one variable directly influences the change in another variable.

# Difference Between Correlation and Causation:

# Correlation: Just because two variables change together doesn't mean one causes the other to change. They may just be related due to another underlying factor or coincidence.

# Causation: One variable directly causes a change in the other.
# Example:
# Correlation: There's a strong correlation between the number of ice creams sold and the number of people who go swimming. However, this doesn't mean that selling ice cream causes people to swim more. Both are influenced by hot weather.

# Causation: If you increase the amount of exercise, it directly causes an improvement in fitness level. In this case, exercise is the cause of the change in fitness.

# Key Points:
# Correlation: Two things are related but one doesn't necessarily cause the other.
# Causation: One thing directly causes the other.

# So, while correlation can suggest a relationship, causation confirms that one variable is directly responsible for the change in another.

In [ ]:
#Que-16. What is an Optimizer? What are different types of optimizers? Explain each with an example

In [ ]:
# -An Optimizer in machine learning adjusts model parameters (like weights and biases) to minimize the loss and improve performance.

# Types of Optimizers:

# Gradient Descent:

# Updates parameters based on the gradient (slope) of the loss function.

# Example: In linear regression, it adjusts weights to reduce the error.

# Momentum:

# Adds previous gradients to speed up learning and avoid getting stuck.

# Example: Helps in faster convergence by accelerating updates in the right direction.

# AdaGrad:

# Adapts the learning rate based on feature frequency, giving larger updates to less frequent features.

# Example: Works well in text classification, where some words appear less often.

# RMSprop:

# Similar to AdaGrad but fixes its decreasing learning rate problem by using a moving average of squared gradients.

# Example: Used in recurrent neural networks (RNNs).

# Adam:

# Combines momentum and AdaGrad to adapt the learning rate and speed up training.

# Example: Commonly used in deep learning for faster convergence.


In [ ]:
#Que-17. What is sklearn.linear_model ?

In [ ]:
# -sklearn.linear_model is a module in scikit-learn that provides linear models for solving regression and classification problems.

# Common Models:

# Linear Regression:
# Used for predicting continuous values (e.g., predicting salary based on years of experience).

# Logistic Regression:
# Used for classification tasks (e.g., spam vs. non-spam emails).

# Ridge & Lasso Regression:
# These are regularized linear regression models. Ridge helps prevent overfitting by penalizing large coefficients, while Lasso can shrink some features' coefficients to zero for feature selection.

# ElasticNet:
# A combination of Ridge and Lasso, used when there’s a need for both types of regularization.


# Why Use sklearn.linear_model?

# These models are simple, fast, and effective when there is a linear relationship between the features and target variable.

In [ ]:
#Que-18. What does model.fit() do? What arguments must be given?

In [20]:
# - The model.fit() function in machine learning is used to train a model using the provided training data. It learns the patterns and relationships between the input features (X) and the target values (y).
# What it does:

# Trains the model: It uses the training data to adjust the model's parameters (e.g., coefficients in linear regression).

# Learns patterns: The model finds patterns between input (X) and output (y) that help it make predictions.
# Arguments to give:

# X: The input data (features) for training. This is usually a 2D array or DataFrame where each row is a sample and each column is a feature.
# y: The target values (labels) for the training data. This is usually a 1D array or Series, where each value corresponds to the label of each sample in X.

# Example:

from sklearn.linear_model import LinearRegression

# Sample data
X = [[1], [2], [3], [4]]  # Features
y = [1, 2, 3, 4]  # Target values

model = LinearRegression()  # Create a model
model.fit(X, y)  # Train the model
# In this example:

# X is the input data (features).

# y is the target data (labels).

# The model learns from X and y using fit().




LinearRegression()

In [ ]:
#Que-19. What does model.predict() do? What arguments must be given?

In [21]:
# - The model.predict() function is used to make predictions based on the features of the test data after the model has been trained.

# What it does:

# Makes predictions: After the model has been trained using model.fit(), you can use model.predict() to make predictions on new, unseen data (test data).

# It generates output values based on the patterns the model learned during training.


# Arguments to give:

# X: The input data (features) for which predictions are to be made. This should be a 2D array or DataFrame with the same number of features as the data used for training.

# Example:
from sklearn.linear_model import LinearRegression

# Sample training data
X_train = [[1], [2], [3], [4]]
y_train = [1, 2, 3, 4]

# Creating and training the model
model = LinearRegression()
model.fit(X_train, y_train)

# New data for prediction
X_new = [[5], [6]]

# Making predictions
predictions = model.predict(X_new)

print(predictions)  # Output: predicted values for X_new

# In this example:

# X_train is used for training the model.

# X_new is the new input data for which we want to make predictions.

# model.predict(X_new) will return the predicted target values based on the patterns the model learned.


[5. 6.]


In [22]:
#Que-20. What are continuous and categorical variables?

In [ ]:
# -Continuous Variables and Categorical Variables are two types of variables used in data analysis and machine learning.

# Continuous Variables:

# These are variables that can take any value within a range and can be measured.

# They usually represent quantities and are numeric.

# Examples:

# Height (5.5 ft, 6.2 ft)

# Weight (50 kg, 60.5 kg)

# Temperature (22.5°C, 30.8°C)


# Characteristics:

# Can have infinite possible values within a given range.

# Arithmetic operations like addition, subtraction, etc., can be performed.


# Categorical Variables:

# These are variables that represent categories or groups and do not have a numerical meaning.

# They can be either nominal (no order) or ordinal (with a specific order).

# Examples:

# Nominal: Gender (Male, Female), Color (Red, Blue)

# Ordinal: Education level (High School, Bachelor's, Master's)


# Characteristics:

# Can be represented by labels or codes.

# Arithmetic operations are not meaningful.


# In summary:

# Continuous Variables: Measurable, numeric values that can have many possible values.

# Categorical Variables: Represent different categories, either with or without order.


In [ ]:
#Que-21. What is feature scaling? How does it help in Machine Learning?

In [27]:
# - Feature scaling is the process of adjusting the range of features in your data so that they are on a similar scale. This is important because some machine learning models are sensitive to the scale of data.

# Why it’s important:

# Prevents dominance of large values: Models may give more importance to features with larger values.

# Improves model performance: For optimization algorithms like gradient descent, scaling helps faster and more stable convergence.

# Common techniques:

# Standardization (Z-score Normalization):
# Scales data to have a mean of 0 and a standard deviation of 1.

import numpy as np
from sklearn.preprocessing import StandardScaler

# Sample numeric data (2D array)
data = np.array([[1, 2], [3, 4], [5, 6]])

# Initialize StandardScaler
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)

# Min-Max Scaling:
# Scales data to a specific range, usually [0, 1].
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample numeric data (2D array)
data = np.array([[1, 2], [3, 4], [5, 6]])

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)
# In short, feature scaling ensures that all features contribute equally, improving model accuracy and performance.


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [ ]:
#Que-22. How do we perform scaling in Python?

In [28]:
# -To perform scaling in Python, we typically use the scikit-learn library, which provides different techniques for scaling numerical data. Below are the common scaling methods and how to apply them:
# Standardization (Z-score Normalization):

# Standardization transforms the data to have a mean of 0 and a standard deviation of 1.
# Steps for Standardization:

from sklearn.preprocessing import StandardScaler
import numpy as np

# Example data (2D array)
data = np.array([[1, 2], [3, 4], [5, 6]])

# Initialize StandardScaler
scaler = StandardScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)

# Min-Max Scaling:

# Min-Max Scaling scales the data to a specific range, usually [0, 1].

# Steps for Min-Max Scaling:

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Example data (2D array)
data = np.array([[1, 2], [3, 4], [5, 6]])

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)

# Explanation of Methods:

# Standardization: Transforms features to have a mean of 0 and a standard deviation of 1. This method works best when the data follows a normal distribution or has outliers.

# Min-Max Scaling: Scales data to a specified range (usually [0, 1]), and is commonly used when you need features on a similar scale, especially for algorithms like neural networks.

# How to Perform Scaling:

# Choose a scaling method based on the nature of your data.

# Import the appropriate scaler from sklearn.preprocessing.

# Fit and transform the data using fit_transform().


# When to Use Each Scaling:

# Standardization is best for most machine learning algorithms, especially those that involve calculating distances (like KNN) or have assumptions about data distribution (like linear regression).

# Min-Max Scaling is useful when you need a specific range, for example, in neural networks.



[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [ ]:
#Que-23. What is sklearn.preprocessing?

In [ ]:
# -sklearn.preprocessing is a module in scikit-learn that provides tools to transform and scale data for machine learning. It includes:

# StandardScaler: Scales features to have a mean of 0 and standard deviation of 1 (Standardization).


# MinMaxScaler: Scales features to a specified range, usually [0, 1].


# LabelEncoder: Converts categorical labels to numeric values.


# OneHotEncoder: Converts categorical data into binary columns (one-hot encoding).


# SimpleImputer: Fills missing values with the mean, median, or most frequent value.



# These tools help improve model performance and make data ready for machine learning.


In [ ]:
#Que-24. How do we split data for model fitting (training and testing) in Python?

In [29]:
# -To split data for model fitting (training and testing) in Python, we use the train_test_split function from scikit-learn's model_selection module. This function randomly splits the dataset into two parts: one for training the model and the other for testing it.
# Steps to Split Data:

# Import the train_test_split function.


# Provide your data (features and target).


# Specify the test size (the proportion of data to be used for testing).


# Optionally, specify the random state to get the same split every time.


# Code Example:
from sklearn.model_selection import train_test_split
import numpy as np

# Sample data (features and target)
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])  # Features (X)
y = np.array([1, 2, 3, 4, 5])  # Target (y)

# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Data (Features):\n", X_train)
print("Testing Data (Features):\n", X_test)
print("Training Data (Target):\n", y_train)
print("Testing Data (Target):\n", y_test)

# Explanation:

# X_train and y_train: Data used for training the model.

# X_test and y_test: Data used for testing the model after it is trained.

# test_size=0.2: 20% of the data will be used for testing, and 80% for training.

# random_state=42: Sets the random seed for reproducibility.


# Why Split Data?

# Training data helps the model learn patterns.

# Testing data helps evaluate the model's performance on unseen data.


Training Data (Features):
 [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
Testing Data (Features):
 [[3 4]]
Training Data (Target):
 [5 3 1 4]
Testing Data (Target):
 [2]


In [ ]:
#Que-25. Explain data encoding?

In [38]:
# - Data encoding refers to the process of converting categorical data into numerical format so that machine learning models can interpret and use it effectively. Many algorithms require numeric inputs, so encoding is crucial for handling categorical variables (like labels, names, or other non-numeric data).
# Types of Data Encoding:

# 1. Label Encoding:

# Converts each category into a unique numeric value.

# Suitable for ordinal data (data with a clear order, like "Low", "Medium", "High").

# Example:
from sklearn.preprocessing import LabelEncoder

data = ['Red', 'Green', 'Blue', 'Green', 'Red']
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)

print(encoded_data)
# Here, Red, Green, and Blue are encoded as 2, 1, and 0 respectively.


# 2. One-Hot Encoding:

# Converts each category into a new binary column (0 or 1).

# Useful for nominal data (data without a specific order, like colors or types).


# 3. Binary Encoding:

# Similar to one-hot encoding but converts categories into binary numbers.

# It reduces the number of columns created compared to one-hot encoding, making it more efficient for high-cardinality categorical variables.


# 4. Frequency Encoding:

# Encodes categories based on their frequency (how often they appear in the dataset).

# Why is Data Encoding Important?

# Machine learning algorithms require numeric data for computation, so categorical data must be encoded.

# It helps in making sense of non-numeric data, ensuring the model can learn from it.



[2 1 0 1 2]
